python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type SimpleNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 20 --lr .01 --epochs 50 --device cuda:1 
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type SimpleNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 16 --lr .01 --epochs 50 --device cuda:1 
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type SimpleNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 12 --lr .01 --epochs 50 --device cuda:1 
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type SimpleNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 10 --lr .01 --epochs 50 --device cuda:1 

python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type TopkNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 30 --topk_num 8 --lr .01 --epochs 50 --device cuda:1
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type TopkNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 16 --topk_num 10 --lr .01 --epochs 50 --device cuda:1
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type TopkNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 16 --topk_num 8 --lr .01 --epochs 50 --device cuda:1 
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type TopkNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 12 --topk_num 6 --lr .01 --epochs 50 --device cuda:1 
python train_net.py --files_df_loc /media/rene/data/adv_gen/MNIST/mnist_normal/files_df.pkl --SAVE_PATH /media/rene/data/adv_gen/MNIST/mnist_normal/feature_models --net_type TopkNetMNIST --IM_SIZE 28 --batch_size 256 --num_filters 10 --topk_num 5 --lr .01 --epochs 50 --device cuda:1 